#exception handling is used to handle exception as well as raise error
#except : used to catch any exception

try:
	5/0
except:
	print("an error occured")
	raise